### ISSUE TITLE
Fall back to JAEGER_AGENT_HOST for JAEGER_SAMPLER_MANAGER_HOST_PORT before localhost

### ISSUE THREAD

**Issue by lw346** [jaegertracing/jaeger-client-java#547]
## Requirement - what kind of business use case are you trying to solve?

Making deployment in a Kubernetes environment simpler, with less configuration needing to be applied to all pods - following DRY principles.

## Problem - what in Jaeger blocks you from solving the requirement?

In the [Jaeger Kubernetes](https://github.com/jaegertracing/jaeger-kubernetes) project, the agents are deployed as a `DaemonSet`, such that they are present on each Kubernetes node.  Each running pod then needs to use the downward API to extract the IP address of the node it is running on as the agent IP.

This results in an environment variable configuration looking like this:

```yaml
env:
- name: JAEGER_AGENT_HOST
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```

If we are using the `RemoteSampler` configuration though, we also expect the agent to be proxying the HTTP sampler API from the collector (which we can derive from the default being `localhost:5778`).  Unlike the agent configuration however, this can only be overridden in a single environment variable: host + port, rather than separate host and port variables.

This means we need in addition to the above, an extra environment variable in each pod:

```yaml
env:
- name: JAEGER_AGENT_HOST
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
- name:  JAEGER_SAMPLER_MANAGER_HOST_PORT
  value: "$(JAEGER_AGENT_HOST):5778"
```

(using runtime substitution to interpolate the first environment variable).

## Proposal - what do you suggest to solve the problem or improve the existing situation?

It would be nice if we could use another fallback mechanism, eg.

1. Look for JAEGER_SAMPLER_MANAGER_HOST_PORT
1. Look for JAEGER_AGENT_HOST, default to port 5778
1. Fall back to localhost:5778

## Any open questions to address

This would, however, be a breaking change in behaviour that people may not be expecting.  If done in conjunction with https://github.com/jaegertracing/jaeger-client-java/issues/521 it could be described as an upgrade in behaviour as well as a name change.

This behaviour should be consistent across the various different client libraries.
