### ISSUE TITLE
How to exclude inner secret request from tracing

### ISSUE THREAD

**Issue by NikolauUB** [jaegertracing/jaeger-client-java#819]
### Discussed in https://github.com/jaegertracing/jaeger-client-java/discussions/818

<div type='discussions-op-text'>

<sup>Originally posted by **NikolauUB** December  7, 2021</sup>
Hello,
I have the following task in Spring boot project: GET request A involves a method which executes GET request B to secret endpoint.
Jaeger with default opentracing configuration traces both requests: A and B as child of A.
I need  to hide request B or mask it for security reason.

My config:

```
opentracing:
  jaeger:
    enabled: true
    log-spans: true
    service-name: my-service
    udp-sender:
      host: localhost
      post: 6831

```
implementation ("io.opentracing.contrib:opentracing-spring-jaeger-web-starter:3.3.1")

My not successfull attempt to influence on span for request B:

```
public class MyFilter extends OncePerRequestFilter {
public MyFilter(){}

@Override
protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
        Span apan = GlobalTracer.get().activeSpan(); //Here only span for request A is available
....
}
```

Thank you for any advices.</div>
